name: sensores
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.0.1
  flutter_sensors: ^1.0.0
  flutter_barometer_plugin: ^0.0.1
  local_auth: ^2.1.3
  battery_plus: ^6.0.3
  light: ^3.0.1
  mic_stream: ^0.7.1+2
  palette_generator: ^0.3.1
  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  speech_to_text: ^6.1.0
  flutter_barometer: ^0.1.0

  #mic_stream: ^0.6.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
